Solved the back button test issue
I was trying to test the ionic back button in protractor and it is
proving really difficult because there are two almost identical divs. I
at first was trying to identify by id, but then when I actually looked
at the generated code, there were two versions with the same id.

Protractor code:

this.showButton = function (arg1) {
var button = expect(element(by.cssContainingText('.button',
arg1)).getText()).toEqual(arg1);
return browser.wait(button, wait);
};
this.showButton('Back');

Generated html:

<div class="nav-bar-block" nav-bar="active">
<ion-header-bar class="bar-royal bar bar-header" align-title="center">
<button id="bB" ng-click="$ionicGoBack()" class="button back-button
buttons button-clear header-item">
<i class="icon ion-ios-arrow-back"></i>
<span id="unique"> </span>
<span class="back-text" style="transform: translate3d(0px, 0px, 0px);">
<span class="default-title">Back</span>
<span class="previous-title hide">undefined</span>
</span>
</button>
<div class="buttons buttons-left header-item">
<span class="left-buttons">
<button class="button button-icon button-clear ion-navicon hide"
menu-toggle="left">
</button>
</span>
</div>
<div class="title title-center header-item" style="transform:
translate3d(0px, 0px, 0px); left: 193px; right: 193px;">
</div>
<div class="buttons buttons-right">
<span class="secondary-buttons">
<button class="button button-stable ng-binding" ng-click="showQR()">
Show My rCard
</button>
&nbsp;&nbsp;
<!-- ngIf: isOnline() && !isSelfServiceEnabled() --><button
class="button button-stable ng-binding" ng-if="isOnline() & amp; & amp;
!isSelfServiceEnabled()" ng-click="showBalance()">
Balance
</button><!-- end ngIf: isOnline() && !isSelfServiceEnabled() -->
</span>
</div>
</ion-header-bar>
</div>
<div class="nav-bar-block" nav-bar="cached">
<ion-header-bar class="bar-royal bar bar-header" align-title="center">
<button id="bB" ng-click="$ionicGoBack()" class="button back-button
buttons button-clear header-item" style="opacity: 0;">
<i class="icon ion-ios-arrow-back"></i>
<span id="unique"> </span>
<span class="back-text" style="transform: translate3d(0px, 0px, 0px);
opacity: 0;">
<span class="default-title">Back</span>
<span class="previous-title hide">undefined</span>
</span>
</button>
<div class="buttons buttons-left header-item" style="opacity: 0;">
<span class="left-buttons">
<button class="button button-icon button-clear ion-navicon hide"
menu-toggle="left">
</button>
</span>
</div>
<div class="title title-center header-item" style="transform:
translate3d(-172.77px, 0px, 0px); left: 68px; right: 68px; opacity:
0;"></div>
<div class="buttons buttons-right" style="opacity: 0;"></div>
</ion-header-bar>
</div>

Protractor failures:

Failures:
1) r2% -- FEATURE_NAME Scenario: We identify and charge a customer
Message:
Expected '' to contain 'Back'.
Stack:
Error: Failed expectation
at E:\xampp\htdocs\cgf\rcredits-mobile\r2.js:212:53
at ManagedPromise.invokeCallback_
(C:\Users\Someone\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1366:14)
at TaskQueue.execute_
(C:\Users\Someone\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
at TaskQueue.executeNext_
(C:\Users\Someone\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2953:27)
at asyncRun
(C:\Users\Someone\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2813:27)
at
C:\Users\Someone\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:676:7
at process._tickCallback (internal/process/next_tick.js:103:7)

The Solution:

this.showBackButton = function (arg1) {

browser.wait(expect(element(by.cssContainingText('div[nav-bar="active"].default-title'),arg1).getText()).toContain(arg1),
wait);
};